version: '3.8'

services:
  webhookshell:
    build:
      context: .
      dockerfile: Dockerfile.windows
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./scripts:/app/scripts
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    networks:
      - webhook-network

networks:
  webhook-network:
    driver: nat
