# Use Windows Server Core 2022 with .NET 8.0 runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0-windowsservercore-ltsc2022 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Install PowerShell Core (pwsh)
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN Invoke-WebRequest -Uri "https://github.com/PowerShell/PowerShell/releases/download/v7.4.1/PowerShell-7.4.1-win-x64.msi" -OutFile PowerShell.msi ; \
    Start-Process -FilePath msiexec.exe -ArgumentList '/i', 'PowerShell.msi', '/quiet', '/norestart' -Wait ; \
    Remove-Item -Path PowerShell.msi ; \
    # Verify pwsh is installed
    pwsh -Command $PSVersionTable

# Build container image
FROM mcr.microsoft.com/dotnet/sdk:8.0-windowsservercore-ltsc2022 AS build
WORKDIR /src

# Copy csproj and restore dependencies
COPY ["src/Webhookshell.csproj", "src/"]
RUN dotnet restore "src/Webhookshell.csproj"

# Copy everything else and build
COPY . .
WORKDIR "/src"
RUN dotnet publish "src/Webhookshell.csproj" -c Release -o /app/publish /p:UseAppHost=true

# Final image
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Webhookshell.dll"]
