name: .NET Build and Publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET 8.0 (LTS)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Create version number
      id: version
      run: |
        BUILD_NUMBER=$(date +%Y%m%d%H%M)
        echo "VERSION=1.0.${BUILD_NUMBER}" >> $GITHUB_ENV
        echo "FILE_VERSION=1.0.0.${BUILD_NUMBER}" >> $GITHUB_ENV
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build the project
      run: dotnet build --configuration Release --no-restore
      
    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish DLL
      run: |
        dotnet publish src/Webhookshell.csproj \
          -c Release \
          -o ./publish/dll \
          -p:Version=${{ env.VERSION }} \
          -p:FileVersion=${{ env.FILE_VERSION }} \
          --no-restore
        
    - name: Publish EXE (Windows Self-Contained)
      run: |
        dotnet publish src/Webhookshell.csproj \
          -c Release \
          -r win-x64 \
          --self-contained true \
          -p:PublishSingleFile=true \
          -o ./publish/exe \
          -p:Version=${{ env.VERSION }} \
          -p:FileVersion=${{ env.FILE_VERSION }} \
          --no-restore
        
    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webhookshell-dll-${{ env.VERSION }}
        path: ./publish/dll
        
    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webhookshell-exe-${{ env.VERSION }}
        path: ./publish/exe