name: .NET Webhook Build and Publish
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # Trigger on version tags
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for release creation
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET 8.0 (LTS)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Create version number
      id: version
      run: |
        BUILD_NUMBER=$(date +%y%j)
        echo "VERSION=1.0.${BUILD_NUMBER}" >> $GITHUB_ENV
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build the project
      run: dotnet build --configuration Release --no-restore
      
    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish DLL
      run: |
        dotnet publish src/Webhookshell.csproj \
          -c Release \
          -o ./publish/dll \
          -p:Version=${{ env.VERSION }} \
          --no-restore
        
    - name: Publish EXE (Windows Self-Contained)
      run: |
        dotnet publish src/Webhookshell.csproj \
          -c Release \
          -r win-x64 \
          --self-contained true \
          -p:PublishSingleFile=true \
          -o ./publish/exe \
          -p:Version=${{ env.VERSION }} \
          --no-restore

    - name: Zip Release Files
      run: |
        cd publish/dll && zip -r ../../webhookshell-dll.zip .
        cd ../exe && zip -r ../../webhookshell-exe.zip .
        cd ../..
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          webhookshell-dll.zip
          webhookshell-exe.zip
        name: Release ${{ github.ref_name }}
        body: |
          Release ${{ github.ref_name }}
          
          - DLL Package: Platform independent .NET assembly
          - EXE Package: Self-contained Windows x64 executable