name: Build, Test, and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 8.0 (LTS)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish DLL
      run: dotnet publish -c Release -o ./publish/dll

    - name: Publish EXE (Windows Self-Contained)
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish/exe

    - name: Create Release Version
      id: version
      run: echo "VERSION=1.0.$(date +%s)" >> $GITHUB_ENV

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v3
      with:
        name: webhookshell-dll-${{ env.VERSION }}
        path: ./publish/dll

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v3
      with:
        name: webhookshell-exe-${{ env.VERSION }}
        path: ./publish/exe
