name: .NET Webhook API Build and Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      dotnet-version: '8.0.x'

  build-and-release:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') }}
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetches all history for all tags and branches
      
    - name: Setup .NET 8.0 (LTS)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Create version number
      id: version
      run: |
        # Create a more unique version using date, time, and run number
        DATE_PART=$(date +%y%j)
        TIME_PART=$(date +%H%M%S)
        RUN_ID="${GITHUB_RUN_ID:-0}"
        
        BUILD_NUMBER="${DATE_PART}.${TIME_PART}.${RUN_ID}"
        echo "VERSION=1.0.${BUILD_NUMBER}" >> $GITHUB_ENV
        echo "TAG_NAME=v1.0.${BUILD_NUMBER}" >> $GITHUB_ENV
        
        echo "Generated version: 1.0.${BUILD_NUMBER}"
        echo "Generated tag: v1.0.${BUILD_NUMBER}"
        
    - name: Create and push tag
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag ${{ env.TAG_NAME }}
        git push origin ${{ env.TAG_NAME }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build the project
      run: dotnet build --configuration Release --no-restore
        
    - name: Publish DLL
      run: |
        dotnet publish src/Webhookshell.csproj \
          -c Release \
          -o ./publish/dll \
          -p:Version=${{ env.VERSION }} \
          --no-restore
        
    - name: Publish EXE (Windows Self-Contained)
      run: |
        dotnet publish src/Webhookshell.csproj \
          -c Release \
          -r win-x64 \
          --self-contained true \
          -p:PublishSingleFile=true \
          -o ./publish/exe \
          -p:Version=${{ env.VERSION }} \
          --no-restore

    - name: Zip Release Files
      run: |
        cd publish/dll && zip -r ../../webhookshell-dll.zip .
        cd ../exe && zip -r ../../webhookshell-exe.zip .
        cd ../..
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        files: |
          webhookshell-dll.zip
          webhookshell-exe.zip
        name: Release ${{ env.TAG_NAME }}
        body: |
          # PowerShell API Webhook ${{ env.TAG_NAME }}

          ## What's New
          - Support for PowerShell script execution via webhooks
          - IP address filtering
          - Time-based triggers
          - Cross-platform support (Windows/Linux)
          - Swagger UI for API documentation and testing
          - Docker and Kubernetes support

          ## Components
          - `webhookshell-dll.zip`: Platform-independent .NET assembly
          - `webhookshell-exe.zip`: Self-contained Windows x64 executable

          ## System Requirements
          - Windows: Windows 10 or later (for EXE package)
          - Other platforms: .NET 8.0 Runtime
          - PowerShell Core (pwsh) or Windows PowerShell

          ## Configuration
          - Update appsettings.json with your webhook configurations
          - Ensure proper permissions for script execution
          - Configure IP allow lists if needed