name: Performance Testing

on:
  workflow_dispatch:
    inputs:
      concurrentUsers:
        description: 'Number of concurrent users to simulate'
        required: true
        default: '50'
      testDuration:
        description: 'Test duration in minutes'
        required: true
        default: '5'
      apiUrl:
        description: 'API URL to test (defaults to local service)'
        required: false
        default: 'http://localhost:80/health'
  pull_request:
    types: [labeled]
  workflow_call:
    inputs:
      concurrentUsers:
        type: string
        required: false
        default: '50'
      testDuration:
        type: string
        required: false
        default: '5'
      apiUrl:
        type: string
        required: false
        default: 'http://localhost:80/health'

jobs:
  performance-test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp rich
        
    - name: Setup .NET 8.0 (for API service)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Build and Start Docker Container for Testing
      run: |
        docker build -t webhookshell:test -f Dockerfile.linux .
        docker run -d --name test-webhookshell -p 80:80 webhookshell:test
        echo "Waiting for container to start..."
        sleep 30
        docker ps
        docker logs test-webhookshell
        curl -v http://localhost:80/health || echo "Health check failed"
    
    - name: Copy load testing script
      run: |
        mkdir -p performance_tests
        chmod +rwx ./performance_tests
        mkdir -p performance_tests/reports
        chmod +rwx ./performance_tests/reports
        cp ./src/scripts/python/webhook_load_tester_linux.py ./performance_tests/
        chmod +rwx ./performance_tests/webhook_load_tester_linux.py
    - name: Debug directory structure
      run: ls -R
      
    - name: Run Performance Tests
      run: |
        cd performance_tests
        python webhook_load_tester_linux.py --api-url ${{ github.event.inputs.apiUrl || 'http://localhost:80/health' }} --concurrent-users ${{ github.event.inputs.concurrentUsers || '50' }} --duration ${{ github.event.inputs.testDuration || '5' }}
            
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: performance-test-reports-linux  # Differentiate from Windows
        path: performance_tests/reports/
        if-no-files-found: error

    - name: Create PR Comment with Test Results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            const fs = require('fs');
            const summaryContent = fs.readFileSync('performance_tests/reports/summary.md', 'utf8');
            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: summaryContent
            });
            
    - name: Display Test Summary for Linux Build
      run: |
        cat performance_tests/reports/summary.md

    - name: Cleanup Docker Container
      if: always()
      run: |
        docker stop test-webhookshell || true
        docker rm test-webhookshell || true

  performance-test-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp rich
        
    - name: Setup .NET 8.0 (for API service)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build and Start Docker Container for Testing
      run: |
          docker build -t webhookshellwin:testwindows -f Dockerfile.windows .
          docker run -d --name test-webhookshell-windows -p 8080:8080 webhookshellwin:testwindows
          echo "Waiting for container to start..."
          powershell -Command "Start-Sleep -Seconds 30"
          docker ps
          docker logs test-webhookshell-windows
          echo "Testing health endpoint..."
          powershell -Command "$containerIp = docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' test-webhookshell-windows; $response = try { Invoke-WebRequest -Uri \"http://$containerIp:8080/health\" -Method Get -UseBasicParsing | Select-Object -ExpandProperty Content } catch { 'FAILED' }; echo 'Health response: ' + $response"
    
    - name: Copy load testing script 
      run: |
        mkdir performance_tests
        copy src\scripts\python\webhook_load_tester_windows.py performance_tests\
        dir performance_tests

    - name: Run Performance Tests
      run: |
        mkdir performance_tests\reports
        cd performance_tests
        python webhook_load_tester_windows.py --api-url ${{ github.event.inputs.apiUrl || 'http://localhost:8080/health' }} --concurrent-users ${{ github.event.inputs.concurrentUsers || '50' }} --duration ${{ github.event.inputs.testDuration || '5' }}
            
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: performance-test-reports-windows  # Differentiate from Linux
        path: performance_tests/reports/
        if-no-files-found: error

    - name: Create PR Comment with Test Results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            const fs = require('fs');
            const summaryContent = fs.readFileSync('performance_tests/reports/summary-windows.md', 'utf8');
            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: summaryContent
            });
            
    - name: Display Test Summary for Windows Build
      run: |
        type performance_tests\reports\summary-windows.md

    - name: Cleanup Docker Container
      if: always()
      run: |
        try { docker stop test-webhookshell-windows } catch { exit 0 }
        try { docker rm test-webhookshell-windows } catch { exit 0 }